### ISSUE TITLE
专享答题不答完，比如只答了4/10题，重新点击学习提示已学习完毕[Bug]: 

### ISSUE THREAD

**Issue by lym0929** [johlanse/study_xxqg#100]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

1.0.37

### 运行环境

Linux

### 运行架构

AMD64

### 运行方式

Docker

### 重现步骤

比如其他答题都完成了，然后专享学习只学习了4题，这个时候再去点击重新学习，就会提示答题已完成，但是专享只答了4题，还有6题没有答

### 期望的结果是什么？

专享答题答完5/10分

### 实际的结果是什么？

只答了4分或9分

**Comment by johlanse** [comment]
@lym0929 4分或9分是答错了一道题，专项现在一天只能答一套题

**Comment by lym0929** [comment]
![image](https://user-images.githubusercontent.com/39184577/193171195-d515dfa3-127b-4ffa-88fa-42fcf9cc0063.png)
![image](https://user-images.githubusercontent.com/39184577/193171226-1169aad8-59eb-4ac2-8bca-9c1720f6c400.png)

**Comment by johlanse** [comment]
@lym0929 因为现在一天只能答一套题，不能重答
