### ISSUE TITLE
能否限制web普通用户只能添加一个账号

### ISSUE THREAD

**Issue by gundamf6** [johlanse/study_xxqg#103]
**环境信息**
<docker>
study_xxqg版本: 1.0.37

**需要添加的功能内容**
<能否限制web普通用户添加账号的数量，目前普通用户可以添加多个账号，没有数量限制，容易造成二次传播，管理员端只能删除，并没有黑白名单限制>

**Comment by hackenfu** [comment]
这个东西应该最好还是自己朋友、信任的人共享吧，如果发现有人乱拉人，直接把这个账号在config里封了完事
