### ISSUE TITLE
帐号的保活定时目测不生效呢。

### ISSUE THREAD

**Issue by piaoyun** [johlanse/study_xxqg#104]
配置里面已经写了如下命令。测试过大写。小写都是失效的

```
## cookie续期保活时间
check_env: "0 */4 * * *"
```

结果发现还是1个小时激活一次帐号保活操作呢

![QQ截图20221010232722](https://user-images.githubusercontent.com/3724475/194901942-7175779e-b0a0-4389-ae8f-feec670c4f78.png)

**Comment by johlanse** [comment]
@piaoyun 写进环境变量，不是配置文件

**Comment by piaoyun** [comment]
运行的是windows的版本呢。windows的exe怎么写到环境变量呢

**Comment by johlanse** [comment]
@piaoyun 自行百度
