### ISSUE TITLE
请问大佬如何添加 只做文章视频、每日答题和专项答题 模式？

### ISSUE THREAD

**Issue by anby1** [johlanse/study_xxqg#106]
每周答题做满了，但不想用多余时间让程序去搜索每周答题的题库。

**Comment by johlanse** [comment]
@anby1 每周答题搜索不需要打开浏览器，大概只需要半分钟不到的时间

**Comment by anby1** [comment]
> 

好的，谢谢大佬

**Comment by anby1** [comment]
> @anby1 每周答题搜索不需要打开浏览器，大概只需要半分钟不到的时间

好的，谢谢大佬
