### ISSUE TITLE
[Bug]: 学习完成后微信推送报错 invalid openid

### ISSUE THREAD

**Issue by toutwoa** [johlanse/study_xxqg#107]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

v1.0.37-SNAPSHOT-76bd499

### 运行环境

Linux

### 运行架构

x86

### 运行方式

Docker-Compose

### 重现步骤

cron 自动学习完成后会进行公众号的推送，推送就会出现无效openid。

### 期望的结果是什么？

正常推送

### 实际的结果是什么？

无法推送

### 日志记录（可选）

```golang
{
	"touser": "c43a3fb727d41af019adae8edbf3fe15",
	"msgtype": "text",
	"text": {
		"content": "xxx学习完成,用时0.1分钟\n当前学习总积分：347\n今日得分：30\n登录：1/1\n文章学习：12/12\n视频学习：6/6\n视频时长：6/6\n每日答题：5/5\n每周答题：0/5\n专项答题：0/1"
	},
	"customservice": {
		"KF_account": "xxqg@xxqg"
	}
}
```

### 补充说明（可选）

touser并不是我在config中填写的super_open_id，这个openid不知道是怎么生成的，我自己使用网页端接口调试程序，修改touser为我自己填写的super_open_id便可以正常推送。

**Comment by toutwoa** [comment]
补充说明 ：
{"touser":"ohIO25rnDF9JUCCxlHb2Y27y9OVY","msgtype":"text","text":{"content":"学习强国助手已上线"},"customservice":{"KF_account":"xxqg@xxqg"}}
这个是正确的，可以正常推送上线信息，就是无法答题结束推送结束信息。

**Comment by toutwoa** [comment]
> @toutwoa 为了解决多用户问题，用户信息会保存一个推送平台登陆者的唯一标识，例如tg平台就是user_id，微信平台就是登陆者open_id，并不是全部都发到管理员处

但是我这个测试号就我一个人关注，这个openid不知道是怎么生成的

**Comment by toutwoa** [comment]
> @toutwoa 为了解决多用户问题，用户信息会保存一个推送平台登陆者的唯一标识，例如tg平台就是user_id，微信平台就是登陆者open_id，并不是全部都发到管理员处

我自己修改了目录下的user.db数据库，手动修改成了我的openid，问题解决，可能是因为号码登录的方式是网页端，所以生成的push_id发生了混乱。

还有一个错误是：微信文本长度超限制，然后会使用模板消息推送，可以考虑以后直接使用模板消息推送。小瑕疵但不影响使用。

**Comment by johlanse** [comment]
@toutwoa 网页登陆会生成随机的uuid

**Comment by toutwoa** [comment]
> @toutwoa 网页登陆会生成随机的uuid

手动改了user.db中的push_id发现，子账号登录上去没有用户了

**Comment by johlanse** [comment]
@toutwoa 因为网页端也需要一个唯一标识啊
