### ISSUE TITLE
大佬，你好，请问协程池这个数值应该怎么设？

### ISSUE THREAD

**Issue by snakwu** [johlanse/study_xxqg#111]
是不是多少个帐号，设多少协程池？还是按内存设置？谢谢

**Comment by zepingwu** [comment]
看commit是配置文件中加个 pool_size参数

**Comment by snakwu** [comment]
> 看commit是配置文件中加个 pool_size参数

我的意思是
# 定时任务运行时协程池的大小
pool_size: 1
后面的数值1对应的是内存大小，还是用户数

**Comment by johlanse** [comment]
@snakwu 目前还有一些问题

**Comment by snakwu** [comment]
> @snakwu 目前还有一些问题

收到，另外大佬，tg群号的推荐连接又失效了
还有一个问题，我添加了保活时间变量到docker-compose.yml文件里，docker无法运行，提示没有这个变量
## cookie续期保活时间
check_env: "0 */2 * * *"

**Comment by zepingwu** [comment]
> 

协程池大小，就是并发任务数量啊。

**Comment by zepingwu** [comment]
> 



> > @snakwu 目前还有一些问题
> 
> 收到，另外大佬，tg群号的推荐连接又失效了 还有一个问题，我添加了保活时间变量到docker-compose.yml文件里，docker无法运行，提示没有这个变量
> 
> ## cookie续期保活时间
> check_env: "0 */2 * * *"

在其它issue里看到要把这个参数放在环境变量里

**Comment by johlanse** [comment]
@snakwu 因为有人在群里找人远程帮他安装，然后马上在别的群做付费代刷，所以把链接撤了

**Comment by snakwu** [comment]
@zepingwu  docker-compose.yml里面就是写的环境变量

**Comment by snakwu** [comment]
> > 
> 
> > > @snakwu 目前还有一些问题
> > 
> > 
> > 收到，另外大佬，tg群号的推荐连接又失效了 还有一个问题，我添加了保活时间变量到docker-compose.yml文件里，docker无法运行，提示没有这个变量
> > ## cookie续期保活时间
> > check_env: "0 */2 * * *"
> 
> 在其它issue里看到要把这个参数放在环境变量里

docker-compose.yml里面的设置就是写进环境变量的

**Comment by snakwu** [comment]
> > 
> 
> 协程池大小，就是并发任务数量啊。

那意思是有多少个帐号，就设置多少数值？

**Comment by johlanse** [comment]
就是并发执行数量，看你自己选择

**Comment by snakwu** [comment]
> 就是并发执行数量，看你自己选择

大佬，如果我是两个用户，那应该是填多少合适

**Comment by johlanse** [comment]
两个用户并不并发有啥关系

**Comment by snakwu** [comment]
> 两个用户并不并发有啥关系

意思是这个并发是多少个线程去完成这个任务？
