### ISSUE TITLE
docker怎么没有arm版了？

### ISSUE THREAD

**Issue by sjkhsl** [johlanse/study_xxqg#116]
**环境信息**

study_xxqg版本:1.0.37

**需要添加的功能内容**
docker怎么没有arm版了？

**Comment by johlanse** [comment]
![image](https://user-images.githubusercontent.com/94164234/196634661-0252591a-6da7-4f68-87a2-85accdff58aa.png)

**Comment by starskyzheng** [comment]
我也看不到，只有4个月之前的版本
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/12579814/197246372-51553cc5-b737-451c-8382-a311495ca018.png">
