### ISSUE TITLE
"视频学习出现异常，稍后可重新学习" 日志太多

### ISSUE THREAD

**Issue by ouyanghd** [johlanse/study_xxqg#12]
当出现这个日志时，程序狂打日志。
原因是 相应的代码else 条件分支没tryCount++ （study.go L: 259）

tryCount 有两个地方，应该两个地方都有问题。

**Comment by johlanse** [comment]
### 应该是已修复了

**Comment by johlanse** [comment]
可以去最新[action](https://github.com/johlanse/study_xxqg/actions/runs/1611347890) 页面下载了

**Comment by ouyanghd** [comment]
嗯，修复了。谢谢
