### ISSUE TITLE
[Bug]: win版设置机器人时出错，希望有老哥帮帮忙🥺

### ISSUE THREAD

**Issue by nokey13** [johlanse/study_xxqg#122]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

1.037 bt3

### 运行环境

Windows (64)

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 运行方式

可执行文件（release的二进制）文件运行

### 重现步骤

电脑已使用clash代理，已按照文档教程填写机器人token以及chat id，但运行时出现图片中的错误，希望大哥们帮忙看看是什么原因，感谢

### 期望的结果是什么？

成功配置tg机器人

### 实际的结果是什么？

电脑端报错，无法配置tg机器人

### 补充说明（可选）

![Uploading 690D91D0-0E3B-4371-BFBA-D1A911B15D66.jpeg…]()

**Comment by qtjay** [comment]
你啥内容都没有提供怎么帮？？

**Comment by nokey13** [comment]
![80144EBF-72C1-48CD-B27A-55696378445C](https://user-images.githubusercontent.com/75052604/198496516-a0e8111b-9bd2-4135-bf7b-d165774eac2f.jpeg)

**Comment by qtjay** [comment]
日志显示telegram连接失败，科学上网配置正常吗？

**Comment by nokey13** [comment]
电脑配置没问题，浏览器可以上谷歌

**Comment by qtjay** [comment]
如果是用浏览器默认代理能行的话,我也不知道怎么解决了, 问作者吧

**Comment by nokey13** [comment]
谢谢

**Comment by johlanse** [comment]
windows不太能从系统变量读取代理，你需要配置proxy到你clash的代理地址，clash默认时http://127.0.0.1:7890
