### ISSUE TITLE
[Bug]: 1.0.37-beta2 docker运行无法跳转学习强国app

### ISSUE THREAD

**Issue by fyu0h** [johlanse/study_xxqg#125]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

1.0.37-beta2

### 运行环境

Linux

### 运行架构

x86

### 运行方式

Docker

### 重现步骤

手机端点击生成链接没有反应，无法跳转APP，继而无法登录使用

chrom F12可见错误代码：
{"code":403,"message":"","data":null,"success":false,"error":"Get \"https://pc-api.xuexi.cn/open/api/sns/sign\": dial tcp: lookup pc-api.xuexi.cn on 127.0.0.11:53: read udp 127.0.0.1:51506-\u003e127.0.0.11:53: i/o timeout"}

### 期望的结果是什么？

希望能够修复

### 实际的结果是什么？

希望能够修复

### docker运行命令或者docker-compose的内容

```golang
version: "3.5"
services:
  xuexi-auto:
    image: jolanse/study_xxqg:latest
    container_name: xuexi-auto
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/opt/config
    ports:
      - 9970:8080
    restart: unless-stopped
```

**Comment by johlanse** [comment]
@fyu0h 你设备的dns问题

**Comment by fyu0h** [comment]
openwrt dns解析配置错误，已解决。
