### ISSUE TITLE
每日答题不可以自动作答，每天只有35分[Bug]: 

### ISSUE THREAD

**Issue by KeFan999** [johlanse/study_xxqg#127]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

1.0.37 beta3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 运行方式

Docker

### 重现步骤

所有配置均正确，采取微信公众号测试号推送学习

### 期望的结果是什么？

学习成绩为40-45

### 实际的结果是什么？

学习成绩为35

### docker运行命令或者docker-compose的内容

```golang
docker run --name study_xxqg --restart always -d -p 8080:8080 -v /etc/study_xxqg/:/opt/config/  jolanse/study_xxqg:latest
```

### 配置信息（可选）

```yaml
按照模板配置，均正确
```

**Comment by KeFan999** [comment]
必须在管理员或者用户登录界面点击开始学习，才能完成每日答题

**Comment by johlanse** [comment]
@KeFan999 请提供每日答题学习的日志

**Comment by KeFan999** [comment]
昨天的问题已经解决！但是又出现了新的问题，无缘无故有别的ipGET一些东西。
![QQ图片20221101153908](https://user-images.githubusercontent.com/115395219/199183092-b5b55d62-03e7-45ec-9849-386847828d9d.png)

**Comment by johlanse** [comment]
部署在内网，本地用可以解决

**Comment by johlanse** [comment]
部署在内网，本地用可以解决
