### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by sevengod007** [johlanse/study_xxqg#128]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

1.0.37-beta3

### 运行环境

其它（请在下方说明）

### 运行架构

其它

### 运行方式

Docker

### 重现步骤

配置文件web登录密码设置为012345（示例），登录时显示用户名密码错误，实际密码为12345，0被舍弃

### 期望的结果是什么？

无

### 实际的结果是什么？

无

**Comment by johlanse** [comment]
@sevengod007 #119

**Comment by sevengod007** [comment]
> @sevengod007 #119
好的，感谢开发者
