### ISSUE TITLE
[Bug]: 添加新用户后，无法登录

### ISSUE THREAD

**Issue by zhengweiqing** [johlanse/study_xxqg#129]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

1.0.38

### 运行环境

Linux

### 运行架构

AMD64

### 运行方式

Docker

### 重现步骤

    # 网页端配置
web:
    # 是否启用网页
  enable: true
    #
  host: 0.0.0.0
  port: 8080
    # 网页端登录账号
  account: admin
    # 网页端登录密码
  password: 123
    # web端登录普通用户的账号密码，支持多个用户,普通用户只能看到自己的信息
  common_user:
    # 代表账号为user,密码为123的普通用户，可添加多个，继续在下面写就好了
    user1: 123
    user2: 123

### 期望的结果是什么？

能否指导一下如何添加新用户？或者做一个用户管理的页面，可以方便添加删除用户帐号

### 实际的结果是什么？

期望得到回复。

**Comment by johlanse** [comment]
并未复现，我测试可以登录

**Comment by zhengweiqing** [comment]
如下图，我在输入密码后，就会提示 “登录失败，请联系管理员” ，只有管理员可以登录。

![image](https://user-images.githubusercontent.com/50610421/199240455-f50f80c8-9f10-4245-be88-870e1f59026e.png)

**Comment by johlanse** [comment]
@zhengweiqing #119
