### ISSUE TITLE
会不会遭到封号呀

### ISSUE THREAD

**Issue by tudoutiaoya** [johlanse/study_xxqg#144]
dear  coder,  担心会被学习强国封号，需要考虑吗

**Comment by johlanse** [comment]
@tudoutiaoya 有顾虑建议不要用

**Comment by tudoutiaoya** [comment]
好的，俺相信你，先用用，嘿嘿嘿。
another question ? 我能二次开发吗，更改前端

**Comment by johlanse** [comment]
@tudoutiaoya 可以，但是请遵守开源协议就行

**Comment by zjdaxue** [comment]
windows版本的web文件在什么地方？

**Comment by johlanse** [comment]
@zjdaxue 静态文件被编译到可执行文件了
