### ISSUE TITLE
[Bug]: 非管理员无法正常登录

### ISSUE THREAD

**Issue by zjdaxue** [johlanse/study_xxqg#147]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

v1.0.38-beta1

### 运行环境

Windows (64)

### 运行架构

AMD64

### 运行方式

可执行文件（release的二进制）文件运行

### 重现步骤

管理员可以正常登录
非管理员无法正常登录

### 期望的结果是什么？

非管理员正常登录

### 实际的结果是什么？

？

**Comment by johlanse** [comment]
无法复现，请提供更多信息
