### ISSUE TITLE
@johlanse 大佬，微信公众号还存在一个问题，以往点查询成绩都只看到自己的成绩，现在查询成绩是看到所有用户的成绩，希望修复一下，谢谢

### ISSUE THREAD

**Issue by snakwu** [johlanse/study_xxqg#148]
@johlanse 大佬，微信公众号还存在一个问题，以往点查询成绩都只看到自己的成绩，现在查询成绩是看到所有用户的成绩，希望修复一下，谢谢

**Comment by KeFan999** [comment]
您好！你绑定的其他用户cookie多久会失效啊

**Comment by KeFan999** [comment]
@snakwu

**Comment by snakwu** [comment]
@KeFan999  这个没有规律，有时三天没登一次，有时一星期

**Comment by johlanse** [comment]
经测试，只有管理员用户可以看到所有人成绩，属于正常现象
