### ISSUE TITLE
添加用户时获取的二维码变成文本格式

### ISSUE THREAD

**Issue by zhuaiice** [johlanse/study_xxqg#154]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

1.0.38-beta1

### 运行环境

Linux

### 运行方式

Docker-Compose

### 重现步骤

更新到最新版后获取二维码的时候变成了qr开头的字符串，不是二维码图片。因而无法扫描获取用户信息进行学习

### 期望的结果是什么？

让二维码信息还是显示为图片格式，谢谢!麻烦大佬

### 实际的结果是什么？

二维码以文本格式显示出来
![16683935810804592297872420231236](https://user-images.githubusercontent.com/28729059/201563828-a54664a3-4026-4bcf-bf7f-942de7c1fcdc.jpg)

**Comment by johlanse** [comment]
#117
