### ISSUE TITLE
ubuntu 20.04下 配置 show_browser: true 不起作用

### ISSUE THREAD

**Issue by ouyanghd** [johlanse/study_xxqg#17]
config.yml里配置了show_browser 为true，仍然不能显示browser。
ps 查看进程启动参数为：chromium-907428/chrome-linux/chrome --type=zygote --no-zygote-sandbox --no-sandbox --headless --headless

# 是否显示浏览器
show_browser: true

**Comment by johlanse** [comment]
你是ubuntu桌面版本吗

**Comment by johlanse** [comment]
因为linux的服务器如果设置了show_browser为true就会报错，所以我在代码中写了linux中设置无效，如果有需要，我可以改回来

**Comment by ouyanghd** [comment]
> 你是ubuntu桌面版本吗

我的是桌面版ubuntu。谢谢

**Comment by ouyanghd** [comment]
验证好了。在ubuntu 20.04下 show_browser: true 能起作用。谢谢
