### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by Zhangxh1011** [johlanse/study_xxqg#18]
![1456310643D85C4378E325DD6D625709](https://user-images.githubusercontent.com/53994620/147461697-ae4ab841-8153-4296-8999-de74b4266bdd.jpg)
![image](https://user-images.githubusercontent.com/53994620/147461712-26017688-2598-451c-a456-e1b1db76dc09.png)

我在容器中运行，打印出二维码之后手机扫码并不行。容器初始镜像选择的centos7.9

**Comment by Zhangxh1011** [comment]
![1456310643D85C4378E325DD6D625709](https://user-images.githubusercontent.com/53994620/147461624-546b98a0-92e0-421b-80a7-ed0b544f2370.jpg)

**Comment by johlanse** [comment]
@Zhangxh1011 请问是否使用最新release版本

**Comment by Zhangxh1011** [comment]
是的

**Comment by johlanse** [comment]
@Zhangxh1011 你可以尝试配置一下tg推送，然后通过tg这边命令运行试一下

**Comment by johlanse** [comment]
我好像复现了，等我修复一下

**Comment by Zhangxh1011** [comment]
好的  非常感谢

**Comment by johlanse** [comment]
你可以去[这里](https://github.com/johlanse/study_xxqg/actions/runs/1626743367) 下载文件试一下了

**Comment by Zhangxh1011** [comment]
非常感谢！由于今天回家了，我明天测试一下
