### ISSUE TITLE
专项答题的时候跳转页面失败

### ISSUE THREAD

**Issue by xiaobao98515** [johlanse/study_xxqg#21]
专项答题的时候跳转页面失败
![Screenshot_1](https://user-images.githubusercontent.com/100138168/154961272-1a0f91d9-18ba-47f0-8221-2a2eda4ef128.png)
![Screenshot_2](https://user-images.githubusercontent.com/100138168/154961287-5c9b158a-9b22-4467-acae-059f062f522b.png)

**Comment by hikysum** [comment]
好像是因为我设置的超时时间只有1s，然后你的网络可能不是很好的原因，我等下把超时时间设置长一点就好了

**Comment by johlanse** [comment]
好像是因为我设置的超时时间只有1s，然后你的网络可能不是很好的原因，我等下把超时时间设置长一点就好了
