### ISSUE TITLE
异常退出

### ISSUE THREAD

**Issue by lanqsh** [johlanse/study_xxqg#22]
Windows下运行一断时间后会退出，再也进不去了
然后换了Linux下运行会异常退出，一次也没成功
![image](https://user-images.githubusercontent.com/12372700/155825646-d41c0511-d705-4552-a2fd-fa0a60659c53.png)

**Comment by lanqsh** [comment]
beta1好像也有问题。。。
![image](https://user-images.githubusercontent.com/12372700/155826604-07c7ab0b-fd33-4499-85b7-d31c31ee949a.png)

**Comment by johlanse** [comment]
@lanqsh 把配置文件最后一行删了应该就可以

**Comment by lanqsh** [comment]
貌似是可以了，但还是报错了
可能我的rp有问题。。。
![image](https://user-images.githubusercontent.com/12372700/155827054-dcfd72ea-ed26-431c-bcdf-a205783c3109.png)

**Comment by johlanse** [comment]
麻烦截图截全一点嘛，个人信息打码就好，顺带看下配置文件

**Comment by lanqsh** [comment]
如果比较麻烦就忽略这个问题吧。。。
![image](https://user-images.githubusercontent.com/12372700/155827576-78ff3776-30eb-4cc0-82eb-c20d03e92afe.png)
![image](https://user-images.githubusercontent.com/12372700/155827620-3934f1c4-72b5-4b64-aeb4-71ac81e50599.png)
![image](https://user-images.githubusercontent.com/12372700/155827681-306bc91d-f963-4731-9598-f98db401e554.png)

**Comment by johlanse** [comment]
这个原因是因为火狐浏览器在有些linux系统运行会缺一些静态链接库，你可以试一下执行  \
```./tools/driver/ms-playwright-go/1.14.0/playwright.sh install-deps``` 
看看能不能运行，因为playwright自带的安装依赖在有些发行版本不能用，如果没法，那就 \
只有一个一个google安装依赖，我之前就安装过。。

**Comment by lanqsh** [comment]
安装失败了。。
这个issue就到这里吧，谢谢您了

[root@lan study_xxqg]# ./tools/driver/ms-playwright-go/1.14.0/playwright.sh install-deps
Cannot install dependencies for this linux distribution!
