### ISSUE TITLE
无法获取登录二维码，一到那步就闪退

### ISSUE THREAD

**Issue by nowstarfall** [johlanse/study_xxqg#23]

**Comment by johlanse** [comment]
使用[常见问题](https://github.com/johlanse/study_xxqg/blob/main/docs/problem.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)提到的第一点获取日志，然后提交issue,不然之说闪退不提供日志没法处理的，感谢你的issue!
