### ISSUE TITLE
二维码未通过pushPlus推送

### ISSUE THREAD

**Issue by ouyanghd** [johlanse/study_xxqg#28]
linux下采用master分支时,登录二维码未通过pushPush推送到微信。没验证windows下的情况。

**Comment by johlanse** [comment]
麻烦提供一下配置文件，关键信息打码即可

**Comment by ouyanghd** [comment]
配置文件如下。谢谢
////////////////////////////////////////////////////////////////
# 刷课模式，默认为3，
# 1：只刷文章何视频
# 2：只刷文章和视频和每日答题
# 3：刷文章和视频和每日答题每周答题和专项答题
model: 3

# 日志等级
# panic
# fatal
# error
# warn, warning
# info
# debug
# trace
log_level: "debug"

# 是否显示浏览器
show_browser: true


push:
  ding:
    enable: false
    access_token: ""
    secret: ""
# 目前仅支持pushplus推送二维码，默认建议使用pushplus推送
# pushplus使用方法见：http://www.pushplus.plus/
  push_plus:
    enable: true
    token: "xxxxxxxxxxxxxxxxxxxxxxxx"

# telegram交互模式配置
tg:
  enable: false
  chat_id: 0
  token: ""
  proxy: ""

# 设置是否定时执行学习程序，格式为cron格式
# "9 19 * * *" 每天19点9分执行一次
# "* 10 * * *” 每天早上十点执行一次
cron: ""

**Comment by ouyanghd** [comment]
我看到现在master分支有推送登录链接，点击链接后会现实登录二维码。
建议直接推送二维码，这样更便利一些。
    var result []byte
    result, err1 := goqrcode.Encode(codeURL, goqrcode.Medium, 256)
    if err1 != nil{
        log.Infoln("二维码错误")
        return nil, err1
    }
    buffer := bytes.NewBuffer(result)
    c.Push("markdown", fmt.Sprintf("![screenshot](%v) \n>点开查看登录二维码\n>请在五分钟内完成扫码", "data:image/png;base64,"+base64.StdEncoding.EncodeToString(buffer.Bytes())))

**Comment by johlanse** [comment]
@ouyanghd 链接可以直接跳转到xxqg的登陆页面啊，二维码还要保存并扫描，感觉链接更方便啊

**Comment by ouyanghd** [comment]
我用的是iphone，在微信里点击推送的链接后，出现提示页面，“点击登录跳转学习强国app"页面链接没反应，还是要保存二维码。但这个二维码需要两步才出现。如果直接推送二维码的话，就一次能看到二维码。
