### ISSUE TITLE
设置TG互动模式，运行后如果梯子有问题，助手会自动关闭。

### ISSUE THREAD

**Issue by Turing-Wu** [johlanse/study_xxqg#30]
使用场景：办公室PC设置掉电恢复后自动开机，助手和梯子设置为开机启动，如果助手启动时梯子还没启动，助手会自动关闭。

**Comment by johlanse** [comment]
已添加*start_wait*配置项，可前往[action](https://github.com/johlanse/study_xxqg/actions/runs/2167422093)下载
