### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by xldc** [johlanse/study_xxqg#33]
runtime error: invalid memory address or nil pointer dereference

**Comment by johlanse** [comment]
@xldc 请提供更加详细的信息

**Comment by 137647821** [comment]
> @xldc 请提供更加详细的信息

我的也是这样，linux环境运行的

**Comment by 137647821** [comment]
> > @xldc 请提供更加详细的信息
> 
> 我的也是这样，linux环境运行的

启动后就直接报这个错误，文章学习模块异常结束、视频学习模块异常结束

**Comment by 137647821** [comment]
![image](https://user-images.githubusercontent.com/51736635/167284121-21c62eda-d2d4-452f-b282-959833518a31.png)
作者解决了踢我一下

**Comment by johlanse** [comment]
@137647821 应该浏览器都没启动成功，你提供一下更上面一点启动浏览器的日志

**Comment by GhostCNZ** [comment]
他没配置浏览器路径。。。。。。

**Comment by johlanse** [comment]
因为linux有时候启动浏览器会确实一些莫名奇妙的静态库，所以要提供完整日志才可以，不然我也没法解决啊

**Comment by 137647821** [comment]
> 因为linux有时候启动浏览器会确实一些莫名奇妙的静态库，所以要提供完整日志才可以，不然我也没法解决啊

之前忙忘了，晚上回去开电脑复现一下吧

**Comment by 137647821** [comment]
确实没配置浏览器路径，会不会是这个原因

**Comment by johlanse** [comment]
不会啊，linux环境会默认下载到目录下的tools文件夹下

**Comment by 137647821** [comment]
> 不会啊，linux环境会默认下载到目录下的tools文件夹下

那晚上弄个完整日志

**Comment by skyreeves** [comment]
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (2 handlers)
[GIN-debug] HEAD   /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (2 handlers)
[GIN-debug] GET    /                         --> github.com/huoxue1/study_xxqg/web.RouterInit.func1 (2 handlers)
[GIN-debug] POST   /auth/login               --> github.com/huoxue1/study_xxqg/web.Login.func1 (2 handlers)
[GIN-debug] POST   /auth/check/:token        --> github.com/huoxue1/study_xxqg/web.CheckToken.func1 (2 handlers)
[GIN-debug] POST   /user/                    --> github.com/huoxue1/study_xxqg/web.addUser.func1 (3 handlers)
[GIN-debug] GET    /user/                    --> github.com/huoxue1/study_xxqg/web.getUsers.func1 (3 handlers)
[GIN-debug] GET    /score                    --> github.com/huoxue1/study_xxqg/web.getScore.func1 (2 handlers)
[GIN-debug] POST   /study                    --> github.com/huoxue1/study_xxqg/web.study.func1 (2 handlers)
[GIN-debug] POST   /stop_study               --> github.com/huoxue1/study_xxqg/web.stopStudy.func1 (3 handlers)
[GIN-debug] GET    /log                      --> github.com/huoxue1/study_xxqg/web.getLog.func1 (3 handlers)
[GIN-debug] GET    /sign/*proxyPath          --> github.com/huoxue1/study_xxqg/web.sign.func1 (3 handlers)
[GIN-debug] GET    /login/*proxyPath         --> github.com/huoxue1/study_xxqg/web.generate.func1 (3 handlers)
[GIN-debug] POST   /login/*proxyPath         --> github.com/huoxue1/study_xxqg/web.generate.func1 (3 handlers)
[GIN-debug] Listening and serving HTTP on 0.0.0.0:80
[2022-05-10 17:02:39] [INFO]: 已采用普通学习模式 
[2022-05-10 17:02:39] [INFO]:  刷课模式，默认为1，
 1：只刷文章何视频
 2：只刷文章和视频和每日答题
 3：刷文章和视频和每日答题每周答题和专项答题 
[2022-05-10 17:02:39] [INFO]: 检测到模式 3 
[2022-05-10 17:02:39] [INFO]: 已配置pushplus推送 
[GIN-debug] [ERROR] listen tcp 0.0.0.0:80: bind: address already in use
2022/05/10 17:02:39 Downloading browsers...
2022/05/10 17:02:39 Downloaded browsers successfully
[2022-05-10 17:02:39] [ERROR]: [core]  初始化chrome失败 
[2022-05-10 17:02:39] [ERROR]: [core]  could not send message: could not send message to server: 
╔════════════════════════════════════════════════════════════╗
║ Host system is missing a few dependencies to run browsers. ║
║ Please install them with the following command:            ║
║                                                            ║
║     npx playwright install-deps                            ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝ 
[2022-05-10 17:02:39] [INFO]: 检测到1位有效用户信息，采用默认用户 
[2022-05-10 17:02:39] [INFO]: 已选择用户:  马赛克
[2022-05-10 17:02:39] [ERROR]: 视频学习模块异常结束 
[2022-05-10 17:02:39] [ERROR]: runtime error: invalid memory address or nil pointer dereference 
[2022-05-10 17:02:39] [ERROR]: 文章学习模块异常结束 
[2022-05-10 17:02:39] [ERROR]: runtime error: invalid memory address or nil pointer dereference 
[2022-05-10 17:02:39] [INFO]: {"data":{"userId":马赛克,"scoreTypeId":0,"scoreTypeName":"总积分","score":15699.0,"time":0,"scoreV2":"0"},"message":"OK","code":200,"error":null,"ok":true}

**Comment by johlanse** [comment]
https://github.com/microsoft/playwright/issues/5893

**Comment by johlanse** [comment]
缺少浏览器依赖，参考上面这个issue安装依赖

**Comment by 137647821** [comment]
./study_xxqg 
WARN[0000] 检测到配置文件可能不存在                                 
ERRO[0000] 写入到配置文件出现错误                                  
ERRO[0000] open ./config/config.yml: no such file or directory 
2022/05/10 22:16:42 Downloading driver to /home/junhui/study_xxqg_linux/tools/driver/ms-playwright-go/1.14.0
2022/05/10 22:16:49 Downloaded driver successfully
2022/05/10 22:16:49 Downloading browsers...
Downloading Playwright build of firefox v1281 - 73.7 Mb [====================] 100% 0.0s 
Playwright build of firefox v1281 downloaded to /home/junhui/study_xxqg_linux/tools/browser/firefox-1281
2022/05/10 22:16:58 Downloaded browsers successfully

这次直接初始化./study_xxqg后出现一个二维码，扫完就退出了。初始化不出配置文件

**Comment by skyreeves** [comment]
我装了个chrome，这次不提示chrome初始化失败了，但文章和视频还是异常结束。我在配置文件里改了个不显示浏览器，然后再运行发现又成功开始学习。但我感觉跟我改配置文件没关系，很谜

**Comment by johlanse** [comment]
@137647821 配置文件初始化失败，可以看下config目录下有没有配置文件，如果有就重新运行一下，如果没有一般就是目录权限问题

**Comment by johlanse** [comment]
@skyreeves linux环境如果没有桌面，然后又配置了显示浏览器，那么也会报莫名其妙的错误

**Comment by johlanse** [comment]
关于*Host system is missing*的解决方案，我用全新的debian系统测试了一下
可以使用以下命令解决
```
sudo apt-get install -y libx11-xcb1 && apt-get install -y libgtk-3-0 && apt-get install -y libxt6 && apt-get install -y libdbus-glib-1.2
```

**Comment by laobei** [comment]
安装下依赖就可以了:   npx playwright install-deps

**Comment by FriendG1973** [comment]
> @137647821 配置文件初始化失败，可以看下config目录下有没有配置文件，如果有就重新运行一下，如果没有一般就是目录权限问题

老哥，在macbook m1上运行源码也遇到了这个问题，已经参考了一些网络上的教程，但还是不知怎么解决，还望您不吝赐教。
