### ISSUE TITLE
http://127.0.0.1:8080 failed to login

### ISSUE THREAD

**Issue by codercplus** [johlanse/study_xxqg#38]
![Snipaste_2022-07-31_09-10-55](https://user-images.githubusercontent.com/63757163/182005644-36fa90d1-8f23-4ea7-90ed-6f4417092ab1.png)

**Comment by johlanse** [comment]
账号密码错误，请查看配置文件账号密码

**Comment by codercplus** [comment]
修改配置文件后，问题已解决。谢谢。
