### ISSUE TITLE
扫描二维码无反映

### ISSUE THREAD

**Issue by blackdarks** [johlanse/study_xxqg#39]
之前正常运行，今天发现扫描二维码后本该弹出网页运行的没有反应，查看运行显示：
[ERR0R]:  新数据失败  
[2022-07-31 10:10:25][ERROR]:SQL 1ogic error:no such column:push_id (1) 
怎么破？

**Comment by johlanse** [comment]
@blackdarks 把config目录的data.db文件删了重新运行一下

**Comment by blackdarks** [comment]
谢谢，试了下问题解决。
