### ISSUE TITLE
更新后不会用了

### ISSUE THREAD

**Issue by lls1043** [johlanse/study_xxqg#40]
有没有介绍，感觉不智能了。

**Comment by johlanse** [comment]
https://johlanse.shhy.xyz

**Comment by lls1043** [comment]
![image](https://user-images.githubusercontent.com/49226217/182500499-659e89aa-6828-4a4d-bc20-b0d59f14e7fa.png)

**Comment by johlanse** [comment]
@lls1043 https://johlanse.shhy.xyz

**Comment by lls1043** [comment]
![image](https://user-images.githubusercontent.com/49226217/182739498-e27eec3d-93e4-4f3d-812e-3472ebc47c59.png)

然后不动了。

**Comment by johlanse** [comment]
密码错误，密码在配置文件里面
