### ISSUE TITLE
用户管理页白屏问题

### ISSUE THREAD

**Issue by LnyChi** [johlanse/study_xxqg#43]
最近版本登录以后点击用户管理页白屏，data返回null未返回数组
![image](https://user-images.githubusercontent.com/53613078/182763911-55f7f52f-f8ea-4ab3-8302-6b3a12a9376a.png)
![image](https://user-images.githubusercontent.com/53613078/182763968-5ff2d2e1-9c67-4e1f-8cbb-f257f4745706.png)

**Comment by johlanse** [comment]
@LnyChi 好的，感谢反馈
