### ISSUE TITLE
armv7 docker支持

### ISSUE THREAD

**Issue by samdong90** [johlanse/study_xxqg#47]
希望增加armv7 docker 支持

**Comment by Promix953** [comment]
上游[playwright](https://github.com/microsoft/playwright)没有内建ARMv7支持
你用的什么设备，换64位系统，纯ARMv7都多少年的老古董了

**Comment by samdong19900909** [comment]
> 上游[playwright](https://github.com/microsoft/playwright)没有内建ARMv7支持 你用的什么设备，换64位系统，纯ARMv7都多少年的老古董了
用的机顶盒nas，就是armv7的，我现在用可执行文件运行，可以运行，就是没有docker方便

**Comment by johlanse** [comment]
可执行文件运行挺好的，还节约资源
