### ISSUE TITLE
反代出现403跨域

### ISSUE THREAD

**Issue by zlhdd108** [johlanse/study_xxqg#49]
使用群晖的docker，配置反代后，点击用户及生成链接都会出现跨域请求403
![image](https://user-images.githubusercontent.com/16465666/183548948-04cab995-2c57-40a2-a522-79bd5501c929.png)
![image](https://user-images.githubusercontent.com/16465666/183602629-2b780535-2c7f-4562-9b66-bd62d21c559f.png)

群晖自己的nginx没办法添加跨域设置，手动添加跨域后reload还是这个提示；如果使用restart，配置文件就恢复原来的了，没办法配置跨域

**Comment by BlackTitle** [comment]
https://juejin.cn/post/6844903678160142343   或许可以试试这篇文章？  不确定是否有效

**Comment by zlhdd108** [comment]
> https://juejin.cn/post/6844903678160142343 或许可以试试这篇文章？ 不确定是否有效

测试了，这个不行

新版本使用暂时没发现跨域的问题，先关闭这个issues了
