### ISSUE TITLE
怎么清除自动安装在c盘的系列应用呢

### ISSUE THREAD

**Issue by Oreo-G** [johlanse/study_xxqg#5]
自动安装在C盘了，一下没注意，有点膈应，请大佬给个指示

**Comment by johlanse** [comment]
直接进入```C:\\user\用户名\AppData\Local\```下删除`ms-playwright`和`ms-playwright-go`文件夹就可以，这个因为playwright自动下载到这里，我也没办法，后面可以尝试配置可执行文件路径来解决
