### ISSUE TITLE
关于docker镜像缩小体积

### ISSUE THREAD

**Issue by Finalweapons** [johlanse/study_xxqg#51]
Golang编译前将CGO_ENABLED设置为0
这样编译出来的程序可以摆脱对C库的依赖
在打包docker的时候可以选择更小的底包镜像

-- 一个菜鸟的拙见，如果已经考虑过这个情况请直接关闭这个issue。感谢

**Comment by johlanse** [comment]
好的，感谢反馈，等我研究研究

**Comment by Promix953** [comment]
1.项目未使用C
2.在.goreleaser.yml中有配置CGO_ENABLED
3.现在镜像体积大是因为在镜像生成过程中执行了init初始化，对chrome等相关组件进行了打包

**Comment by Finalweapons** [comment]
> 1.项目未使用C
> 2.在.goreleaser.yml中有配置CGO_ENABLED
> 3.现在镜像体积大是因为在镜像生成过程中执行了init初始化，对chrome等相关组件进行了打包

如果说是因为Chrome之类的组件导致的确实没有办法了。
我提到的关闭CGO是为了减少编译出来的程序员对系统自身库的依赖，这样编译出来的程序可以运行在更加精简的底包镜像里，比如只有几mb的alpine。
我假象的方法是将编译后的程序放入alpine从而缩小体积，不过没有考虑到playwright-go对环境的要求。
最后，感谢回复
