### ISSUE TITLE
tg推送模式下proxy是必填的吗。如果是用openwrt的passwall在路由器中代理，并没有指定端口，该怎么填配置文件呢？

### ISSUE THREAD

**Issue by summerTony9** [johlanse/study_xxqg#52]
在隔壁的techxuexi项目下，是可以不填proxy的，tg可以正常推送，在本项目下却不行

**Comment by summerTony9** [comment]
![image](https://user-images.githubusercontent.com/48111387/183686981-cf7d3e2f-b6ea-4d66-9c36-261bd8141a1f.png)
![image](https://user-images.githubusercontent.com/48111387/183687171-b033351d-2e45-491d-905f-706bf32a0044.png)
更新：改用clash在路由器中进行代理，依旧报错

**Comment by johlanse** [comment]
@summerTony9 127.0.0.1只能用于本机，你如果用的docker或者两个程序不在同一个设备上，肯定要换成相应的ip

**Comment by summerTony9** [comment]
问题已经解决 
172.17.0.1:7890即可 感谢开发者的回答
