### ISSUE TITLE
每周答题已答完无法自动跳过

### ISSUE THREAD

**Issue by dgutboy** [johlanse/study_xxqg#6]
每周答题所有题已经答完了，但是程序还在里面翻页，卡了10分钟，然后提示答题异常就退出了。大佬解决下呗
![图片](https://user-images.githubusercontent.com/72033168/144691241-eaf860e6-8b26-4857-b6b7-77c27a0e494f.png)

**Comment by johlanse** [comment]
#### 等我研究下（抄）吧，因为我账号是新号，所以不好测试

**Comment by johlanse** [comment]
## 尝试是否已修复
