### ISSUE TITLE
二维码显示不了win系统

### ISSUE THREAD

**Issue by xxf19900504** [johlanse/study_xxqg#61]
下载完成，打开二维码显示不了
<img width="943" alt="Snipaste_2022-08-16_00-49-45" src="https://user-images.githubusercontent.com/90176983/184679097-50431549-b6d2-4d38-a7e8-a1d74377b1c7.png">
。

**Comment by BlackTitle** [comment]
前往 127.0.0.1:8080 进行生成，大概？  我是这么干的

**Comment by xxf19900504** [comment]
> 前往 127.0.0.1:8080 进行生成，大概？ 我是这么干的

tg是怎么个玩法呢，不会了
