### ISSUE TITLE
IPV6使用nginx反代出现错误

### ISSUE THREAD

**Issue by BlackTitle** [johlanse/study_xxqg#62]
IPV6使用nginx反代出现错误，具体表现为使用域名进入后扫码后没有添加，且进入用户管理界面后之前存的用户也没有。
但是使用 127.0.0.1:port 进入后可以查看，使用应该也是可以的。
如果需要截图麻烦告诉我需要哪一部分，我也不知道该提供哪里()，谢谢

**Comment by BlackTitle** [comment]
刚才尝试着使用流量进入  [ipv6]:port 发现和 127.0.0.1:port 一样是能使用的

**Comment by johlanse** [comment]
@BlackTitle 有一个自定义的请求头，xxqg_token，你可以在nginx配置试一下

**Comment by BlackTitle** [comment]
不会配置自定义请求头，我也只是刚接触nginx和代码这些东西 :D
不过根据你的提示找到了 https://juejin.cn/post/6844903678160142343 这篇文章
成功的解决了问题，谢谢兄弟

**Comment by BlackTitle** [comment]
大体意思是nginx把 User_id 中的 _ 给太吞了，导致无法正常的请求
