### ISSUE TITLE
公众号配置好了点登录没链接，docker日志有二维码（已扫码绑定，不至于每次登陆都要docker扫码吧）

### ISSUE THREAD

**Issue by lisonglin980** [johlanse/study_xxqg#67]
我把scheme.html丢到服务器的，网页打开http://域名/scheme.html是有内容的
![image](https://user-images.githubusercontent.com/68982838/185775077-c94f64f9-ad49-4a5f-91ad-5a45d77f41a5.png)
![image](https://user-images.githubusercontent.com/68982838/185775087-73e92e52-ccf6-433d-8b36-ed2932ab3693.png)
![image](https://user-images.githubusercontent.com/68982838/185774871-8cbf3657-fab6-43be-8e89-9c0f9e3650a8.png)
![image](https://user-images.githubusercontent.com/68982838/185775104-db8fecd7-335f-4b5f-a770-fb76d0550021.png)

**Comment by johlanse** [comment]
**invalid template_id**
你的login_temp_id配置的有问题，仔细检查一下模板配置，包括空格之类的

**Comment by lisonglin980** [comment]
> **invalid template_id** 你的login_temp_id配置的有问题，仔细检查一下模板配置，包括空格之类的

两个分别模板是{{data.DATA}}和点我登陆，然后在浏览器中打开！！（中文感叹号）

![image](https://user-images.githubusercontent.com/68982838/185775624-eae75408-9a2b-4b32-9797-e55dab9b0947.png)

![image](https://user-images.githubusercontent.com/68982838/185775707-94b108f6-be58-4771-96d4-2cad21235fa8.png)

**Comment by johlanse** [comment]
@lisonglin980 查看一下配置项有没有空格之类的

**Comment by lisonglin980** [comment]
> 

我又重新添加了模板 还是一样的情况
![image](https://user-images.githubusercontent.com/68982838/185775865-b1431684-1650-42e9-8668-70e6e55f0b6e.png)
![image](https://user-images.githubusercontent.com/68982838/185775871-1dd099f4-224c-48db-a9ec-3e33692cffc5.png)

**Comment by lisonglin980** [comment]
骚瑞 ，我改错配置文件啦。一直在改其他docker的配置文件
