### ISSUE TITLE
视频学习页面无法正常加载

### ISSUE THREAD

**Issue by dgutboy** [johlanse/study_xxqg#7]
目前使用的是win10 64位 amd，浏览器正常打开，切换到视频学习界面无法显示，刷新时有迅速跳过，学完后积分无变化。
![图片](https://user-images.githubusercontent.com/72033168/144810678-448793cf-a85b-4cf2-8d72-63e4ef10e229.png)
![图片](https://user-images.githubusercontent.com/72033168/144810722-2a1d01c2-02b6-4006-94d1-247e1b45d927.png)

**Comment by johlanse** [comment]
好像偶尔会出现学习不能加分的情况，目前没找到原因，可以尝试下重启试试
