### ISSUE TITLE
[Bug]: 自动学习完后微信推送总积分不正确比正确的少五分，点击今日积分获取的积分显示正确，

### ISSUE THREAD

**Issue by wjw054509** [johlanse/study_xxqg#71]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [ ] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

1.0.34

### 运行环境

Linux

### 运行架构

x86

### 运行方式

Docker

### 重现步骤

![Screenshot_20220825-094027_WeChat](https://user-images.githubusercontent.com/85219784/186554879-48c9e8af-6d62-45ff-812e-e82d4bbaed6f.jpg)
自动学习后微信推送的积分显示不正确

### 期望的结果是什么？

可以修复显示不正确的情况

### 实际的结果是什么？

积分显示不正确

**Comment by johlanse** [comment]
积分都是从强国的接口获取的，目前无解，与程序本身无关

**Comment by biewenwoshishui021** [comment]
请教一下，我在linux里装了docker  compose版，登陆ip:8080，提示XXQG登录页了，但提示要我输入账号密码，我输入自己手机号密码，都不行，也试过admin、123456，也不行，请问下，这账号密码，是啥？目前登陆不进去，谢谢作者！

**Comment by johlanse** [comment]
@biewenwoshishui021 请认真查看文档

**Comment by biewenwoshishui021** [comment]
明白了，已登陆。但如何删除用户管理里的账号？目前只能添加，删除不了

**Comment by johlanse** [comment]
> 明白了，已登陆。但如何删除用户管理里的账号？目前只能添加，删除不了

可以在网页端删除了

**Comment by 1653638943** [comment]
> > 明白了，已登陆。但如何删除用户管理里的账号？目前只能添加，删除不了
> 
> 可以在网页端删除了

貌似没找到删除账号的位置

**Comment by johlanse** [comment]
> > > 明白了，已登陆。但如何删除用户管理里的账号？目前只能添加，删除不了
> > 
> > 
> > 可以在网页端删除了
> 
> 貌似没找到删除账号的位置

查看文档
