### ISSUE TITLE
[Bug]: 视频没有学完学习就结束了

### ISSUE THREAD

**Issue by xiehuangpeng** [johlanse/study_xxqg#72]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

latest

### 运行环境

Linux

### 运行方式

Docker-Compose

### 重现步骤

无

### 期望的结果是什么？

视频学习学完

### 实际的结果是什么？

视频学习没有学完

### docker运行命令或者docker-compose的内容

```golang
docker-compose up -d
```

**Comment by xiehuangpeng** [comment]
![526edc90eca915b93e88fdf00bdd2a1](https://user-images.githubusercontent.com/49664464/186802127-18e55d5e-440d-4e31-baa4-b8c88de9e25a.jpg)

**Comment by blackdarks** [comment]
我是Windows环境下，之前好好的，今天开始就各种问题，网页不弹出，然后学习结束发现只有9分，再次打开一闪而退，删除DB数据库文件可以登录，但是依然不能视频分数学完退出
