### ISSUE TITLE
[Bug]: 更换网络后已解决

### ISSUE THREAD

**Issue by gitronsh** [johlanse/study_xxqg#73]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

study_xxqg_windows_amd64.zip

### 运行环境

Windows (64)

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 运行方式

可执行文件（release的二进制）文件运行

### 重现步骤

网页登录正常，可查看积分，点击开始学习后出现“2022/08/26 11:04:19 Downloading driver to D:\Program Files\xxqg\tools\driver\ms-playwright-go\1.20.0-beta-1647057403000”，不得分

### 期望的结果是什么？

修复

### 实际的结果是什么？

问题解决

### 日志记录（可选）

```golang
2022/08/26 11:04:19 Downloading driver to D:\Program Files\xxqg\tools\driver\ms-playwright-go\1.20.0-beta-1647057403000
```

**Comment by johlanse** [comment]
@gitronsh 建议翻译一下这句话
