### ISSUE TITLE
[Bug]: telegram 登录错误

### ISSUE THREAD

**Issue by chenyuyou** [johlanse/study_xxqg#74]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

v1.0.35-SNAPSHOT-d858723 

### 运行环境

Linux

### 运行架构

x86

### 运行方式

Docker

### 重现步骤

获取用户总分错误Get "https://pc-api.xuexi.cn/open/api/score/get": dial tcp 203.107.36.164:443: connect: connection refused

### 期望的结果是什么？

能成功登录

### 实际的结果是什么？

获取用户总分错误Get "https://pc-api.xuexi.cn/open/api/score/get": dial tcp 203.107.36.164:443: connect: connection refused

### docker运行命令或者docker-compose的内容

```golang
docker run --name study_xxqg -d  -v /etc/study_xxqg/:/opt/config/  jolanse/study_xxqg:latest
```

**Comment by chenyuyou** [comment]
有没有人可以指点下

**Comment by johlanse** [comment]
请检查网络
