### ISSUE TITLE
[Bug]: TG点登录链接跳转到app无法正常登录，提示二维码生成失败。扫描TG的二维码登录正常

### ISSUE THREAD

**Issue by allonmymind** [johlanse/study_xxqg#76]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

当前最新版

### 运行环境

Ubuntu

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 运行方式

Docker-Compose

### 重现步骤

重启docker，tg输入/login，点击推送的登录链接跳转到浏览器点链接继续登录跳转到app，再点确认登录

### 期望的结果是什么？

点击链接即可正常登录成功，扫码没有点击跳转方便

### 实际的结果是什么？

实际点击链接登录失败

### docker运行命令或者docker-compose的内容

```golang
version: "3.5"
services:
  xuexi-auto:
    image: jolanse/study_xxqg:latest
    # 容器名
    container_name: xuexi-auto
    environment:
    # 时区
      - TZ=Asia/Shanghai
    # 配置文件路径
    volumes:
      - ./config:/opt/config
    # 映射端口
    ports:
      - 8088:8080
    restart: unless-stopped
```

**Comment by johlanse** [comment]
你可以给一个生成的链接看看，我反正测试了可以正常登录

**Comment by allonmymind** [comment]
> 你可以给一个生成的链接看看，我反正测试了可以正常登录
> 
> 

https://johlanse.github.io/study_xxqg/scheme.html?https%3A%2F%2Flogin.xuexi.cn%2Flogin%2Fqrcommit%3Fshowmenu%3Dfalse%26code%3Dqr%3AD3F63AB3-FB9D-4EDE-884E-D263AB26BEB4%26appId%3Ddingoankubyrfkttorhpou

**Comment by johlanse** [comment]
没问题啊，我好像一不小心登录了，帮我删一下

**Comment by allonmymind** [comment]
> 没问题啊，我好像一不小心登录了，帮我删一下
> 
> 

奇怪了，你的号我已经删掉了。
难道是我用的第三方the的原因？

**Comment by johlanse** [comment]
如果你是安卓系统，你可以更改一下系统的默认浏览器，比如更改为via或者edge之类的

**Comment by allonmymind** [comment]
> 如果你是安卓系统，你可以更改一下系统的默认浏览器，比如更改为via或者edge之类的
> 
> 我是iOS用户😹

**Comment by johlanse** [comment]
那就不清楚了，反正链接肯定没问题的，你可以自己弄一个scheme试一下

**Comment by allonmymind** [comment]
> 那就不清楚了，反正链接肯定没问题的，你可以自己弄一个scheme试一下

![image](https://user-images.githubusercontent.com/18719713/187575513-c240d8fc-4711-4ddc-ac0a-6e85df2b5486.png)
Ok，应该是我自己这边的问题，我再试试看

**Comment by allonmymind** [comment]
> 那就不清楚了，反正链接肯定没问题的，你可以自己弄一个scheme试一下

Tg链接换为chrome 打开现在登陆正常了，谢谢大佬，可以关闭了😀
