### ISSUE TITLE
[Bug]: 专项答题，当答案或提示中包含空格时，可能选错答案

### ISSUE THREAD

**Issue by codercplus** [johlanse/study_xxqg#77]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [ ] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

1.0.35

### 运行环境

Windows (64)

### 运行方式

可执行文件（release的二进制）文件运行

### 重现步骤

专项答题貌似在提示答案中包含空格时会选出错误答案。

![Snipaste_2022-09-01_09-38-19](https://user-images.githubusercontent.com/63757163/187814376-604b6aee-5b31-4b9c-8936-f78025e1d977.png)
![Snipaste_2022-09-01_09-40-02](https://user-images.githubusercontent.com/63757163/187814388-39026b3b-a89d-4906-a2ed-c85e94505ce2.png)
![Snipaste_2022-09-01_09-40-29](https://user-images.githubusercontent.com/63757163/187814400-51ac7297-5dbc-495c-b5d9-6b8fb20d193c.png)

### 期望的结果是什么？

正确地答题

### 实际的结果是什么？

选择了错误的答案

**Comment by johlanse** [comment]
提示信息是什么，答题是根据提示信息来的

**Comment by codercplus** [comment]
> 提示信息是什么，答题是根据提示信息来的

提示信息如下：
![Snipaste_2022-09-01_09-58-27](https://user-images.githubusercontent.com/63757163/187816139-16079c47-19e1-4e12-acb7-4f5fc0e8812b.png)

**Comment by johlanse** [comment]
[ba767ad](https://github.com/johlanse/study_xxqg/commit/ba767ad611d50556bf5e140ba19ee03dab7d1620) 已尝试解决
