### ISSUE TITLE
[Bug]: 网页版xxqg登录后，窗口未显示“开始学习”

### ISSUE THREAD

**Issue by yuyuyueoo** [johlanse/study_xxqg#78]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

v1.0.35（最新版）

### 运行环境

Windows (64)

### 运行架构

x86

### 运行方式

Docker

### 重现步骤

按照windows使用教程操作至“再次进行运行study_xxqg.exe”步骤后，登录“http···8080”显示无法登录成功，通过网页扫码登录后，网页页面未出现“开始学习”小窗口。

### 期望的结果是什么？

正常运行。

### 实际的结果是什么？

未出现“开始学习”小窗口，无法开始学习。

**Comment by yuyuyueoo** [comment]
![412958926388059fcc59541d4965dc9](https://user-images.githubusercontent.com/112743761/188271322-94efd7e7-bc68-4dd8-8b69-e06158e48c74.jpg)

**Comment by yuyuyueoo** [comment]
> ![412958926388059fcc59541d4965dc9](https://user-images.githubusercontent.com/112743761/188271322-94efd7e7-bc68-4dd8-8b69-e06158e48c74.jpg)

按程序操作后如图所示，未显示“开始学习”等小窗口。

**Comment by johlanse** [comment]
我没听懂你想表达的意思

**Comment by yuyuyueoo** [comment]
按照[study_xxqg](https://johlanse.shhy.xyz/)的使用教程挨着操作了，网页登录学习强国程序没有运行。

[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
[GIN-debug] HEAD   /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
[GIN-debug] GET    /                         --> github.com/johlanse/study_xxqg/web.RouterInit.func1 (4 handlers)
[GIN-debug] GET    /about                    --> github.com/johlanse/study_xxqg/web.RouterInit.func2 (4 handlers)
[GIN-debug] POST   /auth/login               --> github.com/johlanse/study_xxqg/web.userLogin.func1 (4 handlers)
[GIN-debug] POST   /auth/check/:token        --> github.com/johlanse/study_xxqg/web.checkToken.func1 (4 handlers)
[GIN-debug] POST   /user                     --> github.com/johlanse/study_xxqg/web.addUser.func1 (5 handlers)
[GIN-debug] GET    /user                     --> github.com/johlanse/study_xxqg/web.getUsers.func1 (5 handlers)
[GIN-debug] DELETE /user                     --> github.com/johlanse/study_xxqg/web.deleteUser.func1 (5 handlers)
[GIN-debug] GET    /score                    --> github.com/johlanse/study_xxqg/web.getScore.func1 (4 handlers)
[GIN-debug] POST   /study                    --> github.com/johlanse/study_xxqg/web.study.func1 (4 handlers)
[GIN-debug] POST   /stop_study               --> github.com/johlanse/study_xxqg/web.stopStudy.func1 (5 handlers)
[GIN-debug] GET    /log                      --> github.com/johlanse/study_xxqg/web.getLog.func1 (5 handlers)
[GIN-debug] GET    /sign/                    --> github.com/johlanse/study_xxqg/web.sign.func1 (4 handlers)
[GIN-debug] GET    /login/*proxyPath         --> github.com/johlanse/study_xxqg/web.generate.func1 (4 handlers)
[GIN-debug] POST   /login/*proxyPath         --> github.com/johlanse/study_xxqg/web.generate.func1 (5 handlers)
[2022-09-03 20:44:13] [INFO]: db_sha: a71c289c9423dd71a88d1fd9db48d51479a4beed8e013f9519c691f524613cff 
[2022-09-03 20:44:13] [INFO]: 当前程序运行版本： v1.0.36 
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[2022-09-03 20:44:13] [INFO]: 正在检查更新. 
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
[GIN-debug] HEAD   /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
[GIN-debug] GET    /                         --> github.com/johlanse/study_xxqg/web.RouterInit.func1 (4 handlers)
[GIN-debug] GET    /about                    --> github.com/johlanse/study_xxqg/web.RouterInit.func2 (4 handlers)
[GIN-debug] POST   /auth/login               --> github.com/johlanse/study_xxqg/web.userLogin.func1 (4 handlers)
[GIN-debug] POST   /auth/check/:token        --> github.com/johlanse/study_xxqg/web.checkToken.func1 (4 handlers)
[GIN-debug] POST   /user                     --> github.com/johlanse/study_xxqg/web.addUser.func1 (5 handlers)
[GIN-debug] GET    /user                     --> github.com/johlanse/study_xxqg/web.getUsers.func1 (5 handlers)
[GIN-debug] DELETE /user                     --> github.com/johlanse/study_xxqg/web.deleteUser.func1 (5 handlers)
[GIN-debug] GET    /score                    --> github.com/johlanse/study_xxqg/web.getScore.func1 (4 handlers)
[GIN-debug] POST   /study                    --> github.com/johlanse/study_xxqg/web.study.func1 (4 handlers)
[GIN-debug] POST   /stop_study               --> github.com/johlanse/study_xxqg/web.stopStudy.func1 (5 handlers)
[GIN-debug] GET    /log                      --> github.com/johlanse/study_xxqg/web.getLog.func1 (5 handlers)
[GIN-debug] GET    /sign/                    --> github.com/johlanse/study_xxqg/web.sign.func1 (4 handlers)
[GIN-debug] GET    /login/*proxyPath         --> github.com/johlanse/study_xxqg/web.generate.func1 (4 handlers)
[GIN-debug] POST   /login/*proxyPath         --> github.com/johlanse/study_xxqg/web.generate.func1 (5 handlers)
[2022-09-03 20:44:13] [INFO]: 已采用定时执行模式 
[2022-09-03 20:44:13] [INFO]: 已开启web配置，web监听地址 ==> 0.0.0.0:8080 
[2022-09-03 20:44:13] [INFO]: 检查更新完成. 当前已运行最新版本. 
[2022-09-03 20:46:34] [INFO]: db_sha: a71c289c9423dd71a88d1fd9db48d51479a4beed8e013f9519c691f524613cff 
[2022-09-03 20:46:34] [INFO]: 当前程序运行版本： v1.0.36 
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[2022-09-03 20:46:34] [INFO]: 正在检查更新. 
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
[GIN-debug] HEAD   /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
[GIN-debug] GET    /                         --> github.com/johlanse/study_xxqg/web.RouterInit.func1 (4 handlers)
[GIN-debug] GET    /about                    --> github.com/johlanse/study_xxqg/web.RouterInit.func2 (4 handlers)
[GIN-debug] POST   /auth/login               --> github.com/johlanse/study_xxqg/web.userLogin.func1 (4 handlers)
[GIN-debug] POST   /auth/check/:token        --> github.com/johlanse/study_xxqg/web.checkToken.func1 (4 handlers)
[GIN-debug] POST   /user                     --> github.com/johlanse/study_xxqg/web.addUser.func1 (5 handlers)
[GIN-debug] GET    /user                     --> github.com/johlanse/study_xxqg/web.getUsers.func1 (5 handlers)
[GIN-debug] DELETE /user                     --> github.com/johlanse/study_xxqg/web.deleteUser.func1 (5 handlers)
[GIN-debug] GET    /score                    --> github.com/johlanse/study_xxqg/web.getScore.func1 (4 handlers)
[GIN-debug] POST   /study                    --> github.com/johlanse/study_xxqg/web.study.func1 (4 handlers)
[GIN-debug] POST   /stop_study               --> github.com/johlanse/study_xxqg/web.stopStudy.func1 (5 handlers)
[GIN-debug] GET    /log                      --> github.com/johlanse/study_xxqg/web.getLog.func1 (5 handlers)
[GIN-debug] GET    /sign/                    --> github.com/johlanse/study_xxqg/web.sign.func1 (4 handlers)
[GIN-debug] GET    /login/*proxyPath         --> github.com/johlanse/study_xxqg/web.generate.func1 (4 handlers)
[GIN-debug] POST   /login/*proxyPath         --> github.com/johlanse/study_xxqg/web.generate.func1 (5 handlers)
[2022-09-03 20:46:34] [INFO]: 已采用定时执行模式 
[2022-09-03 20:46:34] [INFO]: 已开启web配置，web监听地址 ==> 0.0.0.0:8080 
[2022-09-03 20:46:35] [INFO]: 检查更新完成. 当前已运行最新版本. 
[GIN] 2022/09/03 - 20:46:46 | 301 |       947.9µs |       127.0.0.1 | GET      "/"
[GIN] 2022/09/03 - 20:46:46 | 200 |     56.4355ms |       127.0.0.1 | GET      "/static/xxqg/build/home.html"
[GIN] 2022/09/03 - 20:46:46 | 200 |            0s |       127.0.0.1 | GET      "/static/xxqg/build/static/css/main.6f1e3389.css"
[GIN] 2022/09/03 - 20:46:46 | 200 |      1.0253ms |       127.0.0.1 | GET      "/static/xxqg/build/static/js/main.b72f3ffd.js"
[GIN] 2022/09/03 - 20:46:46 | 200 |            0s |       127.0.0.1 | GET      "/static/xxqg/build/manifest.json"
[GIN] 2022/09/03 - 20:46:46 | 200 |            0s |       127.0.0.1 | GET      "/static/xxqg/build/favicon.ico"
[GIN] 2022/09/03 - 20:46:46 | 404 |            0s |       127.0.0.1 | GET      "/static/xxqg/build/logo192.png"
[GIN] 2022/09/03 - 20:46:53 | 200 |      6.6434ms |       127.0.0.1 | POST     "/auth/login"
[GIN] 2022/09/03 - 20:46:56 | 200 |            0s |       127.0.0.1 | POST     "/auth/login"
[GIN] 2022/09/03 - 20:47:28 | 200 |            0s |       127.0.0.1 | POST     "/auth/login"
[GIN] 2022/09/03 - 20:47:31 | 200 |            0s |       127.0.0.1 | GET      "/static/xxqg/build/home.html"
[GIN] 2022/09/03 - 20:47:31 | 200 |         641µs |       127.0.0.1 | GET      "/static/xxqg/build/static/css/main.6f1e3389.css"
[GIN] 2022/09/03 - 20:47:31 | 200 |         641µs |       127.0.0.1 | GET      "/static/xxqg/build/static/js/main.b72f3ffd.js"
[GIN] 2022/09/03 - 20:47:31 | 200 |            0s |       127.0.0.1 | GET      "/static/xxqg/build/manifest.json"
[GIN] 2022/09/03 - 20:47:31 | 200 |            0s |       127.0.0.1 | GET      "/static/xxqg/build/favicon.ico"
[GIN] 2022/09/03 - 20:47:31 | 404 |            0s |       127.0.0.1 | GET      "/static/xxqg/build/logo192.png"
[GIN] 2022/09/03 - 20:47:40 | 200 |            0s |       127.0.0.1 | POST     "/auth/login"
[GIN] 2022/09/03 - 20:48:16 | 200 |            0s |       127.0.0.1 | GET      "/static/xxqg/build/home.html"
[GIN] 2022/09/03 - 20:48:16 | 200 |       417.3µs |       127.0.0.1 | GET      "/static/xxqg/build/static/css/main.6f1e3389.css"
[GIN] 2022/09/03 - 20:48:16 | 200 |       417.3µs |       127.0.0.1 | GET      "/static/xxqg/build/static/js/main.b72f3ffd.js"
[GIN] 2022/09/03 - 20:48:17 | 200 |            0s |       127.0.0.1 | GET      "/static/xxqg/build/manifest.json"
[GIN] 2022/09/03 - 20:48:17 | 404 |            0s |       127.0.0.1 | GET      "/static/xxqg/build/logo192.png"
[2022-09-03 20:56:30] [INFO]: db_sha: a71c289c9423dd71a88d1fd9db48d51479a4beed8e013f9519c691f524613cff 
[2022-09-03 20:56:30] [INFO]: 当前程序运行版本： v1.0.36 
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[2022-09-03 20:56:30] [INFO]: 正在检查更新. 
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
[GIN-debug] HEAD   /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
[GIN-debug] GET    /                         --> github.com/johlanse/study_xxqg/web.RouterInit.func1 (4 handlers)
[GIN-debug] GET    /about                    --> github.com/johlanse/study_xxqg/web.RouterInit.func2 (4 handlers)
[GIN-debug] POST   /auth/login               --> github.com/johlanse/study_xxqg/web.userLogin.func1 (4 handlers)
[GIN-debug] POST   /auth/check/:token        --> github.com/johlanse/study_xxqg/web.checkToken.func1 (4 handlers)
[GIN-debug] POST   /user                     --> github.com/johlanse/study_xxqg/web.addUser.func1 (5 handlers)
[GIN-debug] GET    /user                     --> github.com/johlanse/study_xxqg/web.getUsers.func1 (5 handlers)
[GIN-debug] DELETE /user                     --> github.com/johlanse/study_xxqg/web.deleteUser.func1 (5 handlers)
[GIN-debug] GET    /score                    --> github.com/johlanse/study_xxqg/web.getScore.func1 (4 handlers)
[GIN-debug] POST   /study                    --> github.com/johlanse/study_xxqg/web.study.func1 (4 handlers)
[GIN-debug] POST   /stop_study               --> github.com/johlanse/study_xxqg/web.stopStudy.func1 (5 handlers)
[GIN-debug] GET    /log                      --> github.com/johlanse/study_xxqg/web.getLog.func1 (5 handlers)
[GIN-debug] GET    /sign/                    --> github.com/johlanse/study_xxqg/web.sign.func1 (4 handlers)
[GIN-debug] GET    /login/*proxyPath         --> github.com/johlanse/study_xxqg/web.generate.func1 (4 handlers)
[GIN-debug] POST   /login/*proxyPath         --> github.com/johlanse/study_xxqg/web.generate.func1 (5 handlers)
[2022-09-03 20:56:30] [INFO]: 已采用定时执行模式 
[2022-09-03 20:56:30] [INFO]: 已开启web配置，web监听地址 ==> 0.0.0.0:8080 
[GIN] 2022/09/03 - 20:56:30 | 200 |     58.1085ms |       127.0.0.1 | GET      "/static/xxqg/build/home.html"
[GIN] 2022/09/03 - 20:56:30 | 200 |       742.7µs |       127.0.0.1 | GET      "/static/xxqg/build/static/js/main.b72f3ffd.js"
[GIN] 2022/09/03 - 20:56:30 | 200 |        22.5µs |       127.0.0.1 | GET      "/static/xxqg/build/static/css/main.6f1e3389.css"
[GIN] 2022/09/03 - 20:56:30 | 200 |            0s |       127.0.0.1 | GET      "/static/xxqg/build/favicon.ico"
[GIN] 2022/09/03 - 20:56:30 | 200 |            0s |       127.0.0.1 | GET      "/static/xxqg/build/manifest.json"
[GIN] 2022/09/03 - 20:56:30 | 404 |            0s |       127.0.0.1 | GET      "/static/xxqg/build/logo192.png"
[2022-09-03 20:56:31] [INFO]: 检查更新完成. 当前已运行最新版本. 
[GIN] 2022/09/03 - 20:56:37 | 200 |      6.3882ms |       127.0.0.1 | POST     "/auth/login"
[GIN] 2022/09/03 - 20:56:39 | 200 |            0s |       127.0.0.1 | POST     "/auth/login"
[GIN] 2022/09/03 - 20:56:40 | 200 |            0s |       127.0.0.1 | POST     "/auth/login"
[GIN] 2022/09/03 - 20:56:41 | 200 |            0s |       127.0.0.1 | POST     "/auth/login"
[GIN] 2022/09/03 - 20:56:41 | 200 |            0s |       127.0.0.1 | POST     "/auth/login"
[GIN] 2022/09/03 - 20:56:41 | 200 |            0s |       127.0.0.1 | POST     "/auth/login"
[GIN] 2022/09/03 - 20:57:28 | 200 |         102µs |       127.0.0.1 | GET      "/static/xxqg/build/home.html"

**Comment by johlanse** [comment]
日志没问题啊，登陆之后不是点左上角三个点进入用户管理然后点开始学习嘛

**Comment by johlanse** [comment]
你的截图是qg官网，与study_xxqg有啥关系

**Comment by yuyuyueoo** [comment]
> 日志没问题啊，登陆之后不是点左上角三个点进入用户管理然后点开始学习嘛

![image](https://user-images.githubusercontent.com/112743761/188271735-c8364e2d-ea22-4dca-a15e-ef69394f4976.png)

**Comment by yuyuyueoo** [comment]
> > 日志没问题啊，登陆之后不是点左上角三个点进入用户管理然后点开始学习嘛
> 
> ![image](https://user-images.githubusercontent.com/112743761/188271735-c8364e2d-ea22-4dca-a15e-ef69394f4976.png)

没有办法登录。。

**Comment by johlanse** [comment]
账号密码在配置文件中，你确定你看文档了吗

**Comment by johlanse** [comment]
![image](https://user-images.githubusercontent.com/94164234/188271877-08a53c84-227e-4ee0-818d-ffbd18b5b1a6.png)

**Comment by yuyuyueoo** [comment]
我大概知道怎么用了。。。  外行人，第一次上github。。

**Comment by yuyuyueoo** [comment]
我大概知道怎么用了。。。 外行人，第一次上github。。
我又有一个问题。这个时候我用的是家用电脑登录xxqg，我经过你的贴图知道了需要打开.exe程序后登录http://127.0.0.1:8080/ 网址让其自动操作。但是我工作时间是直接在官网上登录后官方网也左上角出现一小窗口“刷视频、看文章”，直接点击开始学习。（等我工作日再补一个截图）。

**Comment by yuyuyueoo** [comment]
> 我大概知道怎么用了。。。 外行人，第一次上github。。 我又有一个问题。这个时候我用的是家用电脑登录xxqg，我经过你的贴图知道了需要打开.exe程序后登录http://127.0.0.1:8080/ 网址让其自动操作。但是我工作时间是直接在官网上登录后官方网也左上角出现一小窗口“刷视频、看文章”，直接点击开始学习。（等我工作日再补一个截图）。

![微信图片_20220903212015](https://user-images.githubusercontent.com/112743761/188272260-d3536820-3949-4542-a13a-74451907c30c.jpg)

**Comment by johlanse** [comment]
@yuyuyueoo 你可能在找 https://github.com/TechXueXi/techxuexi-js

**Comment by yuyuyueoo** [comment]
> @yuyuyueoo 你可能在找 https://github.com/TechXueXi/techxuexi-js
![image](https://user-images.githubusercontent.com/112743761/188272342-05dbb3a9-60c8-4267-afcf-9bda6def0638.png)
这个应该是正确打开了...

**Comment by yuyuyueoo** [comment]
问题应该关闭了。。谢谢答主。
