### ISSUE TITLE
TG模式下能否支持多用户自动切换学习呢？

### ISSUE THREAD

**Issue by miniers** [johlanse/study_xxqg#8]
如题，现在每次只能通过study指令手动定1个账号来学习，多个账号需要多次执行指令。
或者，能否TG模式和cron模式同时运行呢？TG用来管理查询，cron用来定时顺序 或者并发 执行所有账号的学习🤣
再次感谢大神的工具，好用！

**Comment by johlanse** [comment]
### 已为tg平台添加study_all命令，可去最新[Action](https://github.com/johlanse/study_xxqg/actions/runs/1543957688)下载尝试

**Comment by miniers** [comment]
简单测试了下可以使用，顺便贡献个Dockerfile😁

**Comment by johlanse** [comment]
好的，谢谢

**Comment by johlanse** [comment]
@miniers 如果有空可以再贡献一下docker使用教程，我刚才重构了一下文档

**Comment by miniers** [comment]
好，明天我整理下👌🏻
