### ISSUE TITLE
希望增加两个实用功能

### ISSUE THREAD

**Issue by qtjay** [johlanse/study_xxqg#80]
**环境信息**

study_xxqg版本:1.0.36
推送用的是钉钉群，有十几个人用
目前其实已经很好用了，帮我节省了不少时间，如果能加上下面两个那就更完美了。

**需要添加的功能内容**
一是，推送的二维码链接，能标记一下是谁的二维码，这样人多的情况下，才能每人都点击自己的二维码登录，不会多人都点击同一个码。
二是，希望能在网页端删除过期的用户，目前过期的用户还是在不停的推送消息，而且还无法删除。

**Comment by johlanse** [comment]
功能1不太能实现，因为链接是无状态的，谁都可以点，功能2已实现

**Comment by qtjay** [comment]
感谢大佬回复！我解释一下需求，功能1只是把登录链接加一个过期用户的名字。目前遇到的问题是，目前一台机器上挂十几个人。过期后钉钉消息会推送十几个链接，不加上标记的话很多人都会重复点同一个链接来登录。为了避免这个情况，建议加上名字可以方便大家区分。
