### ISSUE TITLE
[Bug]: 非管理员微信关注微信公众号后点击申请使用管理员微信号无反应

### ISSUE THREAD

**Issue by wjw054509** [johlanse/study_xxqg#84]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [ ] 我已经仔细项目文档!!!
- [x] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

v1.0.36-beta2

### 运行环境

Linux

### 运行架构

x86

### 运行方式

Docker

### 重现步骤

[Bug]: 非管理员微信关注微信公众号后点击申请使用管理员微信号无反应

### 期望的结果是什么？

修正或提供解决方案

### 实际的结果是什么？

修正

**Comment by johlanse** [comment]
![image](https://user-images.githubusercontent.com/94164234/189479810-e34b0167-3137-4dd6-a183-cc4472cd7820.png)
