### ISSUE TITLE
实在抱歉，小白打扰一下，想问一下文档里提到的的config目录在哪里，真的很抱歉，问出这么无知的问题，求解答，万分感谢

### ISSUE THREAD

**Issue by 1071932292** [johlanse/study_xxqg#85]
**环境信息**

study_xxqg版本:

**需要添加的功能内容**

**Comment by BlackTitle** [comment]
下载发行版 解压  启动后出现或者自带。

**Comment by zengping0219** [comment]
文件要全部下载完成 里面就有config文件夹。地址https://github.com/johlanse/study_xxqg

**Comment by 1071932292** [comment]
> 文件要全部下载完成 里面就有config文件夹。地址https://github.com/johlanse/study_xxqg

你好，感谢你的回答，我现在已经全部下载好了，但是进入http://127.0.0.1:8080这个地址输入账号密码后提示我登陆失败，请联系管理员。

**Comment by 1071932292** [comment]
你好，感谢你的回答，我现在已经全部下载好了，但是进入[http://127.0.0.1:8080这个地址输入账号密码后提示我登陆失败，请联系管理员。

**Comment by zengping0219** [comment]
下载https://github.com/johlanse/study_xxqg/releases中相应的启动文件，放刚才那个文件夹，然后打开启动文件之后，就能进网络监控这个后台了。

**Comment by johlanse** [comment]
请完整查看文档
