### ISSUE TITLE
openwrt的passwall在路由器中代理问题，tg如何设置，采用了docker，无论怎么设置，都提示连接被拒绝

### ISSUE THREAD

**Issue by chenyuyou** [johlanse/study_xxqg#90]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

v1.0.35

### 运行环境

Linux

### 运行架构

x86

### 运行方式

Docker

### 重现步骤

passwall中设置代理端口为1081
同时dokcer的ip为172.17.0.2
代理设置为“http://172.17.0.2:1081"
还是不能登录学习

### 期望的结果是什么？

登陆学习

### 实际的结果是什么？

登陆不了

**Comment by johlanse** [comment]
不出意外应该是用docker的网关，而不是docker的IP，还有如果你docker里面确认能上外网，你直接留空proxy就可以
