### ISSUE TITLE
定时任务希望增加多线程学习

### ISSUE THREAD

**Issue by zadishu** [johlanse/study_xxqg#91]
**环境信息**
study_xxqg版本:最新
微信推送

**需要添加的功能内容**
定时任务目前是依次学习，一个号大概20-30分钟，这样人一但多了，比如20个，需要10小时才能学完，

**Comment by johlanse** [comment]
目前可以考虑文章和视频一起学习，但是多人并发暂未考虑

**Comment by lukemin** [comment]
这样会不会容易被封号？
