### ISSUE TITLE
[Bug]:申请使用的消息不应该调用模板

### ISSUE THREAD

**Issue by lisonglin980** [johlanse/study_xxqg#94]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

v1.0.36-beta2

### 运行环境

CentOS

### 运行架构

AMD64

### 运行方式

Docker-Compose

### 重现步骤

最开始的申请使用消息发过来我是可以复制的，就很方便通过后来不知道为什么就变成了消息模板那种，不能复制点不进去的了

### 期望的结果是什么？

像这样可以复制的
![Uploading Screenshot_2022-09-14-01-03-02-582-edit_com.tencent.mm.jpg…]()

### 实际的结果是什么？

![Uploading Screenshot_2022-09-14-01-03-23-210-edit_com.tencent.mm.jpg…]()
不能复制也点不进去

**Comment by johlanse** [comment]
因为客服消息有频率限制，所以只有在发送失败时才会使用模板消息发送
