### ISSUE TITLE
[Bug]: 钉钉推送学习强国登录点不开

### ISSUE THREAD

**Issue by ouyanghd** [johlanse/study_xxqg#97]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

master

### 运行环境

Linux

### 运行架构

AMD64

### 运行方式

源码运行

### 重现步骤

配置钉钉推送
删掉user.db 触发登录流程
程序发送消息，带上登录url到钉钉。
iphone 钉钉收到消息后，点击“点我登录”没反应。

查看了代码是有改动：study_xxqg-master\push\ding.go
L. 27 message = fmt.Sprintf("[点我登录](%v)", "dtxuexi://appclient/page/study_feeds?url="+strings.Split(message, "?")[1])
需要修改为: message = fmt.Sprintf("[点我登录](%v)", message)

### 期望的结果是什么？

点击"点我登录"能打开学习强国app

### 实际的结果是什么？

点击无反应。

**Comment by johlanse** [comment]
因为新版钉钉貌似不支持直接打开强国链接了，所以钉钉也需要加上跳板链接，已修复
