### ISSUE TITLE
功能建议：Web端通过邀请码注册/或者无需登陆进入控制台

### ISSUE THREAD

**Issue by XYZliang** [johlanse/study_xxqg#98]
**环境信息**
ubuntu20
study_xxqg版本:1.0.37

**需要添加的功能内容**
如题所示，因为懒得给自己的同学加账号密码（得开配置文件加，还得重启容器），所以建议可以：
1通过邀请码进行注册，邀请码通过admin账号生成（适合人多）
2无需登录，直接以admin管理员权限进入后台（适合小圈子，大家互相熟悉）

**Comment by johlanse** [comment]
目前web端已支持直接修改文件，已支持热重载，所以暂无更换鉴权方式的打算，study_xxqg也不建议给太多人用
