### ISSUE TITLE
docker版修改配置文件后，会导致容器停止，必须手动重启容器[Bug]: 

### ISSUE THREAD

**Issue by lym0929** [johlanse/study_xxqg#99]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细项目文档!!!
- [X] 我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### studyXxqg 版本

1.0.37

### 运行环境

Linux

### 运行架构

AMD64

### 运行方式

Docker

### 重现步骤

修改配置后自动重启程序时  会导致docker容器停止

### 期望的结果是什么？

容器不停止

### 实际的结果是什么？

容器停止

**Comment by gundamf6** [comment]
应该是故意设置的，修改配置文件后，需要重启docker生效。日志上也写了，修改配置后自动重启，帮你省了一步

**Comment by lym0929** [comment]
> 应该是故意设置的，修改配置文件后，需要重启docker生效。日志上也写了，修改配置后自动重启，帮你省了一步

但问题是没有帮我自动重启docker，他只是帮我的docker容器停止了，停止之后并没有帮我开启回来，所以只要更改配置  站点就死了，要自己上服务器去手动启动容器

**Comment by gundamf6** [comment]
创建docker的时候，有一个 启用自动重新启动 的选项，群晖上是这样写的，别的系统应该类似。

**Comment by gundamf6** [comment]
创建docker的时候，有一个 启用自动重新启动 的选项，群晖上是这样写的，别的系统应该类似。

**Comment by lym0929** [comment]
> 创建docker的时候，有一个 启用自动重新启动 的选项，群晖上是这样写的，别的系统应该类似。

好的，谢谢 我试一下

**Comment by caijinli88** [comment]
> ### 请确保您已阅读以上注意事项，并勾选下方的确认框。
> * [x]  我已经仔细项目文档!!!
> * [x]  我已经在 [问题跟踪器](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。
> * [x]  我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
> 
> ### studyXxqg 版本
> 1.0.37
> 
> ### 运行环境
> linux系统
> 
> ### 运行架构
> AMD64
> 
> ### 运行方式
> Docker服务
> 
> ### 重现步骤
> 修改配置后自动重启程序时 会导致docker容器停止
> 
> ### 期望的结果是什么？
> 容器不停止
> 
> ### 实际的结果是什么？
> 容器停止
> 
> ### docker运行命令或者docker-compose的内容
> _无响应_
> 
> ### 日志记录（可选）
> _无响应_
> 
> ### 配置信息（可选）
> _无响应_
> 
> ### 补充说明（可选）
> _无响应_

执行
docker update --restart=always study_xxqg

**Comment by johlanse** [comment]
@caijinli88 配置文件关闭热重载
